---
site_name: "im-e-system-capacity"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - mermaid2:
      version: 10.9.0
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://Netbeheer-Nederland.github.io/im-e-system-capacity
repo_url: https://github.com/Netbeheer-Nederland/im-e-system-capacity

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
